//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiztool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamTopic
    {
        public int ExamId { get; set; }
        public int TopicId { get; set; }
        public Nullable<short> NumberOfQuestions { get; set; }
        public Nullable<short> MinimumScore { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
