//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiztool
{
    using System;
    using System.Collections.Generic;
    
    public enum QuestionType { Closed, Open };

    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int Id { get; set; }
        public string QuestionText { get; set; }
        public string Codeblock { get; set; }
        public byte QuestionType { get; set; }
        public QuestionType QuestionTypeEnum
        {
            get
            {
                return ((QuestionType)QuestionType);
            }
            set
            {
                QuestionType = (byte)value;
            }
        }
        public string Answer
        {
            get
            {
                string answerText = String.Empty;
                switch (QuestionType)
                {
                    case 0:
                        foreach (Answer answer in Answers)
                        {
                            if (answerText != String.Empty)
                            {
                                answerText += ", ";
                            }
                            answerText += answer.AnswerText;
                        }
                        break;
                    case 1:
                    default:
                        foreach (Answer answer in Answers)
                        {
                            if (answer.IsCorrect)
                            {
                                answerText = answer.AnswerText;
                            }
                        }
                        break;
                }
                return answerText;
            }
        }
        public byte Weight { get; set; }
    
        public virtual Topic Topic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }

    }
}
